### ISSUE TITLE
Autism dataset infomation is off

### ISSUE THREAD

**Issue by randel** [maximilianh/cellBrowser#139]
The info pages for the autism dataset are off.
https://cells.ucsc.edu/?ds=autism

Abstract
This dataset does not seem to have a desc.conf file. Please read https://cellbrowser.readthedocs.io/dataDesc.html or run 'cbBuild --init' to create one

Methods
Loading methods...

Data download
Loading download instructions...

**Comment by matthewspeir** [comment]
Hi, @randel!

Thanks for pointing out this issue. I'll look into this and fix it up.

Matt

**Comment by matthewspeir** [comment]
Hey, @maximilianh.

It looks like something broke with the backwards compatibility with datasets that only had the old summary.html/methods.html/etc. Maybe this is what you meant that email about breaking flat datasets the other day. This affected the following datasets:
* autism
* adultPancreas
* tabulamuris
* 10xMegacell

I was able fix the first three by making a desc.conf and populating it with the information from the summary.html. (In some cases I added additional things that had come out since the summary was made.) The only one I wasn't able to fix was the 10xMegacell datasets as I couldn't find it in /hive/data/inside/cells/datasets/. We can either drop the dataset altogether (it doesn't seem to serve a purpose other than maybe a flex test at >1 million cells, but we also have the larger mouse-organogenesis dataset that fills this role now) or you can fix it. 

Thanks!

**Comment by maximilianh** [comment]
Great thanks ! Yes I forgot to check these datasets, thanks for fixing
them. And yes let’s remove the mega cell dataset, we have enough others now.

**Comment by maximilianh** [comment]
Hi Matt,
Not entirely sure what the concrete bug was, but I think we should not be
doing summary.html/etc anymore anyways, so this is a good time to get rid
of it entirely. Let's always create desc.conf files, even for old datasets.
I've removed the documentation for summary.html, too.

thanks for fixing this on cells-test, can we cbPush these datasets to beta
and request a push?

**Comment by matthewspeir** [comment]
Cool. Removed 10xMegacell from beta and pushed the other 3 over to beta. All their descriptions look good.

I noted some issues with coloring by gene expression on dev in #140, so I'm going to hold off pushing these fixes until that's resolved as well.

**Comment by maximilianh** [comment]
ok #140 is done.

**Comment by randel** [comment]
Thanks for solving this!
