### ISSUE TITLE
tmpFname not defined

### ISSUE THREAD

**Issue by Jeltje** [maximilianh/cellBrowser#147]
pip install cellbrowser
gets me version 0.7 (btw interesting because this github repo only goes up to release 0.6)

in cellbrowser.py
function mtxToTsvGz
these lines went missing, which kills the program ("NameError: name 'tmpFname' is not defined"):
    logging.info("Writing matrix to text")
    tmpFname = outFname+".tmp"

Please re-add?

**Comment by maximilianh** [comment]
Oh darn, I must have not run the tests again... looking...

**Comment by maximilianh** [comment]
No, this function was simply not covered by my tests... were you using
this through cbTool ?

**Comment by maximilianh** [comment]
The problem here again was that I couldn't find a small-ish mtx file
and it's not that easy to create a real Cellranger-formatted mtx file,
as none of the packages can write this format. So I've added a test
now for this, using the big CellRanger 5k sample file, but this means
that my tests are taking longer and longer....

Either way, thanks for this! Released new version 0.7.1

The difference in releases apparently comes from git not automatically
pushing tags. I changed my git settings and this shouldn't happen
again.

**Comment by maximilianh** [comment]
Closed for now, please open if this still doesn't work. I assumed that you used this function through cbTool mtx2tsv

**Comment by Jeltje** [comment]
cbImportCellranger actually:

#  File "/home/jeltjessh/venvs/cb_v07/bin/cbImportCellranger", line 8, in <module>
#    sys.exit(cbCellrangerCli())
#  File "/home/jeltjessh/venvs/cb_v07/lib/python3.6/site-packages/cellbrowser/convert.py", line 430, in cbCellrangerCli
#    crangerToCellbrowser(options.datasetName, options.inDir, options.outDir, options.noMat)
#  File "/home/jeltjessh/venvs/cb_v07/lib/python3.6/site-packages/cellbrowser/convert.py", line 321, in crangerToCellbrowser
#    matFname = importCellrangerMatrix(inDir, outDir)
#  File "/home/jeltjessh/venvs/cb_v07/lib/python3.6/site-packages/cellbrowser/convert.py", line 273, in importCellrangerMatrix
#    mtxToTsvGz(matFname, geneFname, barcodeFname, outExprFname)
#  File "/home/jeltjessh/venvs/cb_v07/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 5423, in mtxToTsvGz
