### ISSUE TITLE
Firefox-specific errors

### ISSUE THREAD

**Issue by ljpearlman** [maximilianh/cellBrowser#148]
I've installed cellbrowser locally (cellbrowser 0.5.49 with Apache httpd 2.4.41 on Fedora 29) and, after converting some Seurat files, I've found that I can view them perfectly well with Chrome and Safari, but not with Firefox (the specific Firefox version I'm using is 70.0.1 on MacOS Mojave, but I've had a few colleagues try with different Firefox versions, and they've seen the same thing).

Specifically, Firefox gives me the message:
```
internal error: cbDraw.drawDots - colorArr is not 1/2 of coords array. Got 17 color values but coordinates for 7343 cells.
```
when trying to view https://staging.rebuildingakidney.org/demo/cellbrowser/?ds=16-2D5A

This seems to come from the function drawDots in maxPlot.js:
```
if (colArr.length !== (coords.length>>1))
            alert("internal error: cbDraw.drawDots - colorArr is not 1/2 of coords array. Got "+pal.length+" color values but coordinates for "+(coords.length/2)+" cells.");
```
When I set a breakpoint in my Firefox browser, the values of coords.length and colArr.length are 14686 and 3720, respectively (in Chrome, the values are 14686 and 7343, which is half of 14686).

I suspect something's going wrong when the Cluster metadata is read. I'm attaching a couple screenshots of debugger sessions -- the actual size of the metaFields/Cluster.bin.gz file on disk is 3720 bytes; in Chrome, it looks like the file is read in and then inflated, but in Firefox, it looks like the inflation doesn't work.

Here's a debugger screenshot in Firefox, stopped just after `comprBytes` should have been expanded into `bytes` - you can see that `bytes` is smaller than expected.

<img width="1435" alt="Screen Shot 2019-11-21 at 2 48 53 AM" src="https://user-images.githubusercontent.com/8785501/69333239-27cbd780-0c0d-11ea-8dfb-b176e687117f.png">

Here's the same thing in Chrome - you can see the metadata has the same name and md5, but here the sizes indicate that `bytes` actually has been uncompressed.

<img width="1577" alt="Screen Shot 2019-11-21 at 12 37 10 AM" src="https://user-images.githubusercontent.com/8785501/69333184-0ec32680-0c0d-11ea-8b89-a3668fee8849.png">

Another data point: the datasets on cells.ucsc.edu all look fine to me in all browsers; the files on sansomlab.github.io look fine to me in Chrome but give me errors (although not exactly the same errors as my local files) in Firefox.

Any help in getting this to work in Firefox would be greatly appreciated.

**Comment by maximilianh** [comment]
Oh, this bug report is pure gold! Thanks and sorry for not testing on
Firefox anymore, I used to, and since I never found anything (except text
drawing performance, which I need to get back to), I stopped testing on
Firefox.

I'll get back to you tomorrow.

**Comment by maximilianh** [comment]
Hmm... the fact that the javascript on the UCSC browser is working fine
indicates to me that this is something I've fixed before. We did some
testing on Firefox a long time ago and I remember having fixed something
that had to do with this error message.... Can you tell me first on which
version you are ( I really really need to put the version information
somewhere into the code...) ? How did you install your browser?

If you're not sure or you installed with Conda, could you install the
cellbrowser package with pip?

pip install cellbrowser --upgrade

and then update just the javascript code files on your webserver:

cbUpgrade --code -o <your top level html output directory>

**Comment by ljpearlman** [comment]
Thanks! For the version that those screenshots are from, I installed all the prerequisites into conda and then did a pip install (from within conda) of cellbrowser, which resulted in version 0.5.49:

```
ls -d ~/.conda/envs/cellbrowser/lib/python3.8/site-packages/cellbrowser-*
/home/laura/.conda/envs/cellbrowser/lib/python3.8/site-packages/cellbrowser-0.5.49.dist-info
```

Yesterday, though, I decided to do a clean install from sources; this is what I did (deriva is our own python library that I've been using to get some of the description text that goes into cellbrowser.conf):

```
conda create -y -n cb-src r pip
conda activate cb-src
conda install -y -c bioconda -c conda-forge r-seurat icu
git clone https://github.com/maximilianh/cellBrowser.git
cd cellBrowser
python3 setup.py install
pip install deriva
```

This was commit 85ca009208bf70116a02d914c6f0fde7dce049e3; I got the same results with this version as with the 0.5.49 version.

**Comment by maximilianh** [comment]
Thanks! I can totally reproduce this and I admit that this is rather
mysterious... still looking...

**Comment by maximilianh** [comment]
OK, I have found a few things that resemble this bug here:
https://github.com/GMOD/jbrowse/issues/667#issuecomment-161991228

The problematic files here are already compressed. Somehow, Chrome and
Safari handle it, but Firefox has a problem, it seems to compress twice.
You can see that something is going on by looking at the file size: after
the download, in the network tab, before Javascript even touches the file,
the file size is 3720 (correct) in Chrome, but 3743 (wrong) in Firefox (the
gzip header has around 20-24 bytes). You can't reproduce it with wget. The
file has "Content-Encoding: gzip" on your server, where as on my server, gz
files don't have "Content-Encoding: gzip". Could you have a look at your
Apache config and look for the mod_deflate settings? Did you activate gzip
compression for all files or just certain files?
On our server, the default config came with this line:
    AddOutputFilterByType DEFLATE text/html text/plain text/css
text/javascript application/x-javascript
This restricts compression to file types where it makes most sense.

An easy way to check if my suspicion that this has something to do with
Apache compression would be to temporarily deactivate the mod_deflate
module entirely in apache (a2dismod) restart apache and retry. If it's
working then, we know what the problem is and you can set the Apache
configuration.

Another workaround may be that I remove the .gz extension from all
files...? This would probably break compatibility with older installations
though.

**Comment by maximilianh** [comment]
Here are a few other ideas on how to disable compression for certain file
extensions
https://stackoverflow.com/questions/9249243/how-to-disable-apache-gzip-compression-for-some-media-files-in-htaccess-file

**Comment by ljpearlman** [comment]
That was it! Compression was also causing Apache to ignore Range headers in Firefox requests (so each individual-gene request for exprMatrix.bin would download the whole file; cellbrowser seemed to do the right thing with that, but it was a big performance hit).

**Comment by maximilianh** [comment]
Great!! Phew. Glad it worked.

I think I should have a much stronger warning when range headers are not
supported by the server... trying to cope with this may lead people to
think that cell browser is slow...

**Comment by maximilianh** [comment]
Added visible warning now to user when webserver doesn't support byte range requests. Also extended error message when file is found to be compressed twice. Thanks for this excellent report.
