### ISSUE TITLE
Font-size for cluster title

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [maximilianh/cellBrowser#165]
![Screen Shot 2020-04-11 at 11 44 07 PM](https://user-images.githubusercontent.com/22722805/79062352-9b1ec600-7c4e-11ea-872f-27be88703f5c.png)

I am trying to chnage the font size for the cluster title via. https://github.com/maximilianh/cellBrowser/blob/0d6d0e203a1e25c49d3522254ff223364a6a98f5/src/cbPyLib/cellbrowser/cbWeb/js/maxPlot.js#L265

However, it is not working. Any thoughts?

Thanks!!

**Comment by maximilianh** [comment]
Yes, this is not the right location to change the font size of the labels.
Hey, I just remember, we have a nice pull request open to change the font
and the size, by Nikolai, unfortunately, we never really decided to go
forward with it. However, it will give you a good idea on how to do it:
https://github.com/maximilianh/cellBrowser/pull/145

Can you tell us a little what type of font you prefer? Maybe we can change
the default. Nikolay's seemed a little bit hard to read, but otherwise his
font is really nicer than ours.

**Comment by Parul-Kudtarkar** [comment]
@maximilianh thanks for a quick response. In our case we have clusters that are spatially close to each other that the fonts overlap. We want to reduce the font size. It would be good if we can change the font size label via. config files

**Comment by matthewspeir** [comment]
@maximilianh could this request be addressed by the 'metaOpt' setting:
```
metaOpt = {
        "cell" : {"fontSize":"80%"}
}
```

I see we have it in the cellbrowser.conf for the autism dataset: https://github.com/ucscGenomeBrowser/cellbrowser-confs/blob/ed517a20ed4a04fe412e81831159b0a022170f0b/autism/cellbrowser.conf#L73. Or does that setting not do what I think?

**Comment by maximilianh** [comment]
Oops, I think this is incorrect in the example. We've only used it once, so
it never got tested.

The code renames this from metaOpt to just "opt", my bad, a bad choice for
finding it quickly.

I think it does what you think it does, but should be metaOpt = {'fontSize'
: "80%"}, I believe. See the code:
---
           var styleAdd="";
            if (metaInfo.opt!==undefined) {
                var opt = metaInfo.opt;
                if (opt.fontSize!==undefined)
                    styleAdd = ";font-size:"+metaInfo.opt.fontSize;
            }

            htmls.push("<div class='tpMetaValue'
style='width:"+(metaBarWidth-2*metaBarMargin)+"px"+styleAdd+
                "' data-field-name='"+metaInfo.name+"' id='tpMeta_" + i +
"'>&nbsp;</div>");
            htmls.push("</div>"); // tpMetaBox
---

Does this solve this particular problem?

Otherwise: We can extend it to cover other cases, e.g. font colors or any
other CSS attributes.

**Comment by matthewspeir** [comment]
Thanks, Max. I would assume that it addresses the request in this ticket, so I'm going to go ahead and close this. @Parul-Kudtarkar feel free to reopen if more is needed here.

**Comment by maximilianh** [comment]
Hi @Parul-Kudtarkar <https://github.com/Parul-Kudtarkar> if you're still
using the Cell Browser, do you have URL for us where we can have a look
around? I'm curious how you're using the options.

nikolay has a branch with various changes to the font/size of the cluster
labels.
