### ISSUE TITLE
select cells based on intersection of annotations

### ISSUE THREAD

**Issue by Gibbsdavidl** [maximilianh/cellBrowser#191]
Is this possible?  It's essentially making cell selections based on annotation set operations.

I want to select a set of cells within cluster A as background  (param == 'X', cluster=='A'),
and compare to the remaining cells within cluster A (param != 'X' and cluster =='A' or even param == 'Y').

Thanks!

**Comment by maximilianh** [comment]
Did you try Edit - Find Cells ?

**Comment by Gibbsdavidl** [comment]
Oh wow!  Thanks.  That's just what I was looking for.

-dave

**Comment by Gibbsdavidl** [comment]
One suggestion is to have a 'is not equal to' selection for enumerated types.

**Comment by maximilianh** [comment]
I'm glad you asked. It's very hard to get an idea for me which features
people find useful...

**Comment by Gibbsdavidl** [comment]
Actually, this would be super useful feature for me... so I'm going to reopen the issue.  :-)  Hope that's OK.

I have a cluster where cells are annotated with 4 categories (A,B,C,D) and if you want to select category A,
it's pretty easy  (select cells: cluster == 1, category == A). But if you want to compare A vs others, it's 
more difficult  (cluster == 1, category != A).

Thanks!
-dave

**Comment by maximilianh** [comment]
Isn’t there a “is not equal” operator ? Oh... did I forget to add that ???

**Comment by Gibbsdavidl** [comment]
Oh, uh, yes. There is not an  "is not equal"  (!=) operator.

-dave

**Comment by maximilianh** [comment]
Oops, sorry. I've added it now, you can find it on the Github develop branch and also on cells-test.gi.ucsc.edu. Is this for your own cell browser installation? Or for a dataset on cells.ucsc.edu ?

Also, I'd love to understand better the use case: is this for comparing two non-clusters?

@matthewspeir since we've covered it here, not sure, but maybe we need an internal redmine ticket for it, too? I don't remember what our plan was for handling Github issues w/r to releases.

**Comment by matthewspeir** [comment]
I believe this has made it into a release. Closing for now.
