### ISSUE TITLE
`Edit|Export Selected` not working

### ISSUE THREAD

**Issue by lzx325** [maximilianh/cellBrowser#218]
I selected some cells in the demo `cortex development` dataset and tried `edit|export selected` but nothing happens after then. Is there supposed to be a pop-up dialog to save the selected cells' UMI?

**Comment by maximilianh** [comment]
This was fixed in the development version last week but we haven't fixed
the public site yet. are you looking to use this on your own cell browser
or do you need it on cells.ucsc.edu ?

If only on the public site, you can use cells-test.gi.ucsc.edu for today to
have it working there, we'll try to fix the public site ASAP.

many thanks for your email!

**Comment by maximilianh** [comment]
OK great, let us know how the setup goes. I imagine you are aware of
cellbrowser.readthedocs.org with the setup instructions. It should be
smooth, but if you find places that need improvement, let us know.

**Comment by maximilianh** [comment]
Hi Izx325, thanks for closing the ticket. I imagine this means that
the installation worked?

**Comment by lzx325** [comment]
Yes, it works. Thank you for the help!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
