### ISSUE TITLE
getDatasetNameFromUrl() in cellBrowser.js converts most datasetName to lowercase

### ISSUE THREAD

**Issue by bugacov** [maximilianh/cellBrowser#219]
The logic in this function will converts pretty much all datasets to lowercase so if one creates a dataset w/ uppercase name it throws an error saying that it cannot find the dataset when passing a URL with a dataset name (last argument) in uppercase

**Comment by maximilianh** [comment]
Yes, and this is intentional, because at UCSC we only allow lowercase
dataset names. I agree that I should document this and possibly allow a
different handling.

The reason for all-lowercase is that we serve the datasets using an Apache
rewrite rule, which allos URLs like cortex-dev.cells.ucsc.edu and DNS does
not support case, it may come from a time when there were still 7bit
codepages around.

What do you suggest that I do for non-UCSC users?

1) throw an error when an upper case is used in a dataset name
2) deactivate the lower casing on non-UCSC systems

Is that upper case / lower case question very important for your use case?
Could you live with all-lowercase datasetnames, knowing that you could make
the URLs easier to read (I can document how we configured our Apache, I
think it's a one-line .htaccess file)

Thanks for opening this ticket. It's definitely something I should have
expected happening to other users...

**Comment by bugacov** [comment]
Hi Maximilian,
Thanks for your quick reply!!
Your option 2) :

2) deactivate the lower casing on non-UCSC systems

Is what we suggest implementing.
The part of the URL after the ?ds= is case sensitive and works well for when I tested modifying your code in my installation.

We’d really appreciate if you can implement that change.
Thanks again for your help!!
Best,
Alejandro.

From: Maximilian Haeussler ***@***.***>
Reply-To: maximilianh/cellBrowser ***@***.***>
Date: Wednesday, May 26, 2021 at 1:57 AM
To: maximilianh/cellBrowser ***@***.***>
Cc: Alejandro Bugacov ***@***.***>, Author ***@***.***>
Subject: Re: [maximilianh/cellBrowser] getDatasetNameFromUrl() in cellBrowser.js converts most datasetName to lowercase (#219)

Yes, and this is intentional, because at UCSC we only allow lowercase
dataset names. I agree that I should document this and possibly allow a
different handling.

The reason for all-lowercase is that we serve the datasets using an Apache
rewrite rule, which allos URLs like cortex-dev.cells.ucsc.edu and DNS does
not support case, it may come from a time when there were still 7bit
codepages around.

What do you suggest that I do for non-UCSC users?

1) throw an error when an upper case is used in a dataset name
2) deactivate the lower casing on non-UCSC systems

Is that upper case / lower case question very important for your use case?
Could you live with all-lowercase datasetnames, knowing that you could make
the URLs easier to read (I can document how we configured our Apache, I
think it's a one-line .htaccess file)

Thanks for opening this ticket. It's definitely something I should have
expected happening to other users...

**Comment by maximilianh** [comment]
Hi,
I've deactivated lower casing, in cellbrowser.js line 7083 now for non-UCSC
servers. I cannot test this myself, because all my webservers run at UCSC.
If you want, you can checkout the "develop" branch and then run
src/cbUpgrade --code -o <htmlOutputDirectory> and try if this solves your
problem.

thanks
Maxy

**Comment by ljpearlman** [comment]
Hi,

I think `!pageAtUcsc()` should just be `pageAtUcsc()` here -- as written, this will lower-case non-UCSC URLs (and not lower-case UCSC URLs).

```
        if (datasetName && datasetName!=="adultPancreas" && !pageAtUcsc())
                    datasetName = datasetName.toLowerCase();
```

Thanks,

- Laura

**Comment by maximilianh** [comment]
Yes, this makes sense. I've changed this now. you can get the change from
Github. It's not too unlikely that we'll have a release next week, too.
Thanks!

**Comment by ljpearlman** [comment]
That worked, thanks!
