### ISSUE TITLE
quickGenesfile config

### ISSUE THREAD

**Issue by biocaitao** [maximilianh/cellBrowser#225]
We had a long name. We set cellbrowser.conf by adding
quickGenesFile = "quickGenes.csv"
metaOpt = {"Cluster_field" : {"fontSize": "5px"}}
But it seems still too long.  The default config displays 4 genes per row, can it be changed to 3 genes per row?
Thanks

**Comment by maximilianh** [comment]
Hi, do you have a link for this dataset so I can look at it and we can
think about how to solve this?

Can I ask what the gene name is? Usually they’re pretty short , at least
human symbols are, is this another organism ?

Otherwise, I can add an option to a) reduce the number of columns as you
say or b) to increase the size of the left side bar. May there are other
solutions, like cutting of the names at x characters or allowing specifying
“short names”.

**Comment by matthewspeir** [comment]
Hi, @biocaitao ! It looks like the image you wanted to share didn't get attached to your comment. 

However, we recently made some changes to support longer gene names in the quickGenesFile. Can you give v1.2.0 a shot and let us know if that fixes things for you? Once you've installed the new version via pip, you can upgrade the software on an existing cell browser instance using cbUpgrade --code -o <your_cb_dir>

**Comment by matthewspeir** [comment]
Closing this ticket for now. Feel free to reopen if more discussion is needed or open a new ticket if you run into new issues.
