### ISSUE TITLE
[Feature Request] Find Cells by named selection

### ISSUE THREAD

**Issue by alexlenail** [maximilianh/cellBrowser#260]
it's possible to select cells -> Edit>name selection, but then it isn't possible to Edit>Find Cells by the named selection. 

I'd really like to select the cells in some region of a UMAP with a particular cell type label.

**Comment by maximilianh** [comment]
Hi Alexander, thanks for the feedback. I'm confused why you used "name
selection" first... Can't you just search for "cluster=xxx" and hide
everything but these cells, then select from them?

So what you want to do is really "select the cells in some region of a UMAP
with a particular cell type label"? (Is there a particular dataset where
you're doing this? not important, just curious)

**Comment by alexlenail** [comment]
I'm in a situation where my celltype annotation prediction tool wasn't perfectly accurate, so e.g. in the astrocyte cluster on the umap, there are a small number of cells labeled as each other celltype, which I believe is a mistake. I want to select all the cells in the astrocyte cluster which are not labeled as astrocytes and relabel them.

**Comment by maximilianh** [comment]
I see. You want to select all cells within a given area (ideally we would
have a lasso tool for that, sorry), and want to find all that are not
labeled in some way.

Hmmm... what are you going to do once you can do this? the Cell Browser
being a "browser", there is no good tool to make changes to the underlying
data...

**Comment by alexlenail** [comment]
Thanks @maximilianh . I'm trying cellxgene now. Let's close this issue if it's out of scope for cellBrowser. This is definitely a feature that's needed though!

**Comment by maximilianh** [comment]
Yes, I understand, cellxgene is a local app, it can read and write your
local data file. You annotate cells, cellxgene can write your annotations
to the data file, all fine.

I'm not sure what cellbrowser would do with information like this... it has
no server backend. It has no access to the data file... it could maybe give
you a stable link to the new result, but how would you share that with
others? Or save the information permanently?

Cellbrowser is great if you want to serve an h5ad file (that you previously
annotated with e.g. cellxgene) to a larger audience, people who want to
look at your data. Cellbrowser is not an annotation tool, by design, it
wasn't built for that...

**Comment by alexlenail** [comment]
Thanks @maximilianh -- that clarifies things.
