### ISSUE TITLE
'Find Cells' doesn't work

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#63]
@maximilianh When I open the 'Find Cells' pop-up from the 'Edit' drop-down, I can't seem to actually find any cells after selecting a field and entering a filter value. If I hit 'enter' on my keyboard or click 'OK' nothing happens. The pop-up doesn't close and no filter is applied.

Steps to reproduce:

- Open 'cortex-dev' dataset
- Under 'Edit' drop-down click 'Find Cells'
- For 'cell annotation field' select 'Age_in_Weeks' and set the next drop-down to be 'is greater than' and the value to be '21.00'
- Hit 'enter' on the keyboard or click 'ok'
- Notice that nothing happens

**Comment by maximilianh** [comment]
I've fixed this now for gene expression values. Still working on it. Will take some more time.

**Comment by maximilianh** [comment]
I've added a LOT of code for find cells, You can now remove fields and the current status is written to the URL and also the dialog is recreated with your current filtering options.

But... I still haven't fixed this issue with numeric fields. Will do tomorrow.

**Comment by matthewspeir** [comment]
Awesome! Those were actually things I was going to suggest in some new tickets, but you've already added them! :)

Thanks!

**Comment by matthewspeir** [comment]
Any update on fixing 'Find Cells' for numerical values? Thanks!

**Comment by maximilianh** [comment]
Haven't gotten to that yet... sorry...

**Comment by matthewspeir** [comment]
No problem. Was just wondering if there were any updates. :)

**Comment by maximilianh** [comment]
Update before you think I'm not doing anything on this:
I think I've spent two full days on this now in total. Still ongoing. It
moves the assignment of bins to numbers from Python into Javascript.
Somehow I'm too stupid to do the discretization of the numbers in
javascript even though I had it all working in Python before.

**Comment by maximilianh** [comment]
Given Hiram's Wiggle experience, I should have known that storing numbers
in bins instead of the original numbers (which is what I used to do with
meta fields that are numbers), is a really bad idea....

**Comment by maximilianh** [comment]
OK, after three long days, this should be working now. you can try it on
cells.ucsc.edu/dev, I've only tested with the cortex-dev dataset yet.

cortex-dev.cells.ucsc.edu/dev

Let me know what else I should fix. Here are a few ideas:

1) when you come back to Find - cells, shouldn't you find the same state as
last time again? I find it annoying I always have to reclick everything
2) the input box should be cleared when you change the field
3) I wonder if there should be some way to select if the criteria are ANDed
or ORed, when it searches for these cells.

I wonder if it should have some sort of command line, so you can type a
query instead of this clicking business, but that's a feature for another
day.

>

**Comment by maximilianh** [comment]
The changes to number meta data fields have not been committed yet,
I'm worried that I've broken something fundamental.

Oh and by the way multi-selecting cells now is working again, it shows
reasonable stuff when you mouse over the field. The histogram is
fixed, too.

**Comment by matthewspeir** [comment]
Thanks, Max!

Few things:

1.  Doesn't look like settings are saved in the 'Find Cells' pop-up. If I apply a set of filters and then come back, the fields I chose are still there, but the values are not.
2. Related to (1), it looks like if the first cell annotation field selected in 'Find Cells' is a numerical field, then field name is never saved upon applying the filter and reopening the pop-up. It could be that this applies to all numerical fields, but the issue in (3) is preventing me from seeing the other numerical fields in the 'Find Cells' pop-up.
3. It looks like if there are over 22 'cell annotation' fields (such as in https://hgwdev.gi.ucsc.edu/~mspeir/cb_GSE84465/?ds=Quake_Glioblastoma_GSE84465, where I think I have 35 -40) then only the first 22 are shown in the 'Find Cells' drop-down menu.

**Comment by maximilianh** [comment]
> Doesn't look like settings are saved in the 'Find Cells' pop-up. If I apply a set of filters and then come back, the fields I chose are still there,
> but the values are not.
I think I fixed this in today's release.

> Related to (1), it looks like if the first cell annotation field selected in 'Find Cells' is a numerical field, then field
> name is never saved upon applying the filter and reopening the pop-up. It could be that this applies to all numerical fields,
> but the issue in (3) is preventing me from seeing the other numerical fields in the 'Find Cells' pop-up.
Should be OK.

> It looks like if there are over 22 'cell annotation' fields (such as
> in https://hgwdev.gi.ucsc.edu/~mspeir/cb_GSE84465/?ds=Quake_Glioblastoma_GSE84465, where I think I have 35 -40) then
> only the first 22 are shown in the 'Find Cells' drop-down menu.
this I hope had something to do with this broken meta data file which
was due to the bug in metaCat. It seems to be fixed now.

Can you update and re-run cbBuild and let me know if this is indeed all fine?

It's incredible how slow I am with fixing these things compared to
writing them. It took a day to write this dialog and probably give to
fix the edge cases. Sigh. I guess that's always the same with
software.

**Comment by matthewspeir** [comment]
Everything looks to be fixed in the latest, 0.4.63.

**Comment by maximilianh** [comment]
I meant to write “three days” not “give”. Wow now I’m making typos as
autocorrect was on, even though I type on the laptop.

Thanks Matt for helping me getting these things fixed!
