### ISSUE TITLE
duplicates in list of recent genes

### ISSUE THREAD

**Issue by slowkow** [maximilianh/cellBrowser#65]
I selected IL6 a few times, and now my list of recent genes has the same gene (IL6) listed multiple times.

I love the idea to keep a list of recent genes! I think that's probably one of the most useful lists you can make. But it would be nice to de-duplicate it:

![image](https://user-images.githubusercontent.com/209714/51639536-24a18580-1f2f-11e9-8253-81bb95e2c94d.png)

You can see the behavior on our page: https://immunogenomics.io/cellbrowser

**Comment by maximilianh** [comment]
Oops, there is code that is supposed to avoid exactly this, but apparently
it's not working. Will fix.

**Comment by maximilianh** [comment]
Should be fixed now. Thanks for your report! I haven't released to pip yet,
but will do that tonight (you're using github or pip to install?)

**Comment by slowkow** [comment]
I think we're using github. No problem either way.

Thanks for the quick fix!

**Comment by matthewspeir** [comment]
FYI @maximilianh this issue is coming up again on a recent instance of the cell browser I have up here: https://genome-test.gi.ucsc.edu/~mspeir/cb_demo/?ds=oligodendrocyte_ms_GSE118257.

See:
![cellbrowserRecentGeneRepeats](https://user-images.githubusercontent.com/11509990/54774019-07540500-4bc8-11e9-9e01-4a237047660d.png)

**Comment by matthewspeir** [comment]
Well, whatever issue I was seeing last March seems to be fixed now on cells.ucsc.esu. Closing.
