### ISSUE TITLE
Can't search by gene symbol in my cell browser

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#81]
For some reason, I can't search by gene symbol in my cell browser: https://genome-test.gi.ucsc.edu/~mspeir/cb_pancreas_csv_v4/?ds=HCA_Pancreas_Aging

Data for this browser is in: /hive/users/mspeir/cellbrowserTest/pancreas/new_metadata_test/matrix_files/cbScanpyOut_pancreas_aging 

Do you know why? In the docs, you say "ENSG and ENSMUSG gene identifiers will be translated automatically to symbols." (https://cellbrowser.readthedocs.io/tabsep.html?highlight=gene%20symbol), but that doesn't seem to be happening here. It tried it on datasets that have ENSG* IDs with version numbers and those without and it doesn't seem to work in either case.

**Comment by maximilianh** [comment]
Yes, this is because there is

geneIdType='symbols'

In your cellbrowser.conf file. It should be 'auto' to get the auto-translation.

Oops. the default was symbol/gencode-human! I chose a stupid default.
Changed it now. Thanks!

Release 0.4.49 (committed a ton of other code for the MS update, will
email around later on that)

**Comment by matthewspeir** [comment]
I think this has been fixed.
