### ISSUE TITLE
AttributeError: 'Raw' object has no attribute 'transpose'

### ISSUE THREAD

**Issue by Xparx** [maximilianh/cellBrowser#85]
Trying to convert a scanpy object and got an issue with the Raw object in my data

```
$ cbImportScanpy -i adata_calc_kendalltau.h5ad -o testThings
INFO:root:Creating testThings
INFO:root:Using ad.raw expression matrix
INFO:root:Writing scanpy matrix (885 cells, 15287 genes) to testThings/exprMatrix.tsv.gz
INFO:root:Transposing matrix
Traceback (most recent call last):
  File "/home/andreas/.virtualenvs/cellbrowser/bin/cbImportScanpy", line 10, in <module>
    sys.exit(cbImportScanpyCli())
  File "/home/andreas/.virtualenvs/cellbrowser/lib/python3.6/site-packages/cellbrowser/convert.py", line 510, in cbImportScanpyCli
    scanpyToCellbrowser(ad, outDir, datasetName, skipMatrix=options.skipMatrix)
  File "/home/andreas/.virtualenvs/cellbrowser/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 2905, in scanpyToCellbrowser
    anndataToTsv(adata, matFname)
  File "/home/andreas/.virtualenvs/cellbrowser/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 2810, in anndataToTsv
    mat = mat.transpose()
AttributeError: 'Raw' object has no attribute 'transpose'
```
After setting `raw=None` it seems to work.

**Comment by maximilianh** [comment]
Many thanks for this! I didn't run into it. I just changed the exporter to
default to the raw data and I'm still unsure if this is the best choice. I
probably should add an option for this behavior...

**Comment by maximilianh** [comment]
I must admit, I have no idea how the anndata.raw attribute is supposed to
be used. It's not a copy of the complete anndata object. It's not just the
matrix. It may be a copy of the matrix and the vars? I cannot find any
documentation either, except a few examples. I create my anndata objects
with the read() functions. Those don't seem to have .raw attributes. I'll
have to dig into the scanpy source code. If you have a high-level view of
how this .raw attribute is supposed to be used, I'm interested.

**Comment by maximilianh** [comment]
Every time I'm digging into scanpy, I'm frustrated how complex this library
is at its base. Someone really likes fancy python-specific syntax
constructs and building complex cathedrals of objects without documenting
the big picture.

I struggle with the most basic things, e.g. does ad.transpose() also
transpose the raw matrix? Looking at the code, I doubt that it does.

The only documentation that I can find is here:
https://github.com/theislab/anndata/blob/master/anndata/base.py#L1017

Do you know how I can make an example scanpy object with something in the
raw attribute?

**Comment by maximilianh** [comment]
OK, thank you, you brought up a topic that has been brewing for a while.
The big problem was with scanpy input that for many datasets you could not
color on genes that were not highly variable, even if they are well-known
marker genes because I had no real support for raw data export.

I've made these changes now:

- cbScanpy keeps the .raw data, uses it by default for the matrix export
but writes it to the .h5ad file and has the useRaw option in scanpy.conf to
change that default behavior
- cbScanpyImport does not use the raw data by default, but now has the -r
option to export the raw data for the matrix. I wonder if I should change
it and make the raw matrix export the default.

I tested cbScanpy with pbmc_small and then used cbScanpyImport on the
result, both with the -r option and without the -r option and confirmed
that the matrix differs.

It would be great if you could do a "pip install cellbrowser --upgrade" and
try it on your dataset. Release 0.4.59. I hope I didn't break something
else this time.

**Comment by Xparx** [comment]
Hi,

Thanks for the quick response and sorry for my slow response. It looks like you found solutions to the first questions you had.
I will try out the new solution when I get to my laptop this evening.

In general the raw data will probably contain many more genes than the anndata object so it might be worth using it by default.

**Comment by maximilianh** [comment]
I agree. I've changed it now such that cbImportScanpy exports the raw data
by default, outputs a warning if there is no raw data and falls back to
processed data. I've removed the -r option and added the --proc option
which will use the processed matrix. Let me know if this doesn't work for
your data. release 0.4.60, just run the pip command I mentioned to upgrade.
Closing this issue now, feel free to reopen when there is a problem related
to the raw data.

>
