### ISSUE TITLE
updated files aren't always replaced by cbBuild

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#87]
Example, I updated the summary.html for a dataset and then ran cbBuild. I expected that the new summary.html would overwrite the old one, but that doesn't seem to be the case. 

I had to actually go in and remove the old file and then run cbBuild to update the summary page. 

I can't seem to consistently recreate this issue. Will let you know when I can and provide more details then.

**Comment by maximilianh** [comment]
Yes, html files will never be overwritten, there should have been an info
message about that. This is because html files will be edited by the user
and if I overwrite them, I risk overwriting what they wrote. Does that
sound OK?

**Comment by matthewspeir** [comment]
Hmm. Maybe an HTML overwrite option for cbBuild would be helpful? I guess I thought that the directory where you're running cbBuild would be like the 'source of truth' where all of the original files live. If I wanted to change something, I would change it there and then use cbBuild to copy it over.

Though I talked to Will yesterday and he seemed to think it would work as you were envisioning: after you ran cbBuild, you would edit the copied HTML files. So, maybe I'm wrong here and cbBuild should keep behaving the way it is.

**Comment by maximilianh** [comment]
Hmm, how about this: we could think about not assuming that html files
are hand-generated. We could assume that html files are generated from
some more structured description, like some text file that looks like
tagStorm or .ra and that includes stuff like:

- the title
- the PMID
- the abstract
- etc

and all the html files would be generated from that?

This would be much more work, but it would make sure that in the
future, all html will look similar and can be easily updated when we
change the templates...

**Comment by maximilianh** [comment]
Wait! I misunderstood you! I always copy over the summary.html in the
target when you run cbBuild. This is only an issue with
cbSeurat/cbScanpy & Co.

I think this is something else. It's certainly not intentional. For
me, this always happens due to browser caching. To avoid you can
either:
load the page in Chrome Dev mode and switch off the cache (under "network")
Or I could add a checksum of these pages to the URL. That would
completely avoid the problem.

**Comment by matthewspeir** [comment]
Yeah, I had run cbBuild in my cbScanpy output directory, which copied over the unedited, default summary.html. I then edited the summary.html file in that directory and then ran cbBuild and the edited summary.html file wasn't copied over. I even tried a hard refresh (cmd+shift+r) in Chrome, but it still wasn't updated. 

Not sure what was happening. I can try a little bit of debugging to see if I can replicate it.

**Comment by maximilianh** [comment]
I believe that what happened is that the summary.html was copied over but
your chrome cashed it. shift-reload somehow doesn't work in this case, as
the file is loaded from javascript. I don't know why Chrome doesn't really
clean, it seems like it should, but it doesn't. I'm just adding md5 sums to
all URLs, so that should fix it. Thanks for pointing it out.

**Comment by maximilianh** [comment]
I meant "cache" not "cash". Either way, I've spent a few hours now to add
md5s to virtually all URLs. The md5 of the full dataset is based on the
config, all the htmls, the matrix and the meta. So if any of these changes,
the version of the dataset will change. All URLs to any file in a dataset
have this version added, so that should force a cache refresh in Chrome.
Not pushed yet, haven't tested it enough yet.

**Comment by matthewspeir** [comment]
@maximilianh Have you pushed these changes yet? If so, I'll give them a test and close this ticket if everything looks good.

**Comment by maximilianh** [comment]
Yes, many things have md5s now, but a few still haven't, e.g. a change to
gene symbols (but not gene identifiers) currently won't update the cache,
but the things you noticed, html files etc, should now force a cache update
when you change them.

**Comment by matthewspeir** [comment]
I haven't encountered this in a while, so closing.
